// Generated by Haxe 4.0.5
(function ($hx_exports, $global) { "use strict";
class Summer {
	constructor(a,b) {
		this.a = a;
		this.b = b;
	}
	print() {
		return this.a + this.b;
	}
}
$hx_exports["Summer"] = Summer;
class Main {
	static getSummer() {
		return Summer;
	}
	static cippa(x) {
		return { a : x + 1};
	}
	static main() {
		console.log("src/Main.hx:27:","Hello, world!");
	}
}
$hx_exports["Main"] = Main;
Main.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, {});
