/* tslint:disable */// Generated by Haxe TypeScript Declaration Generator :)

export class Summer {
	constructor(a: number, b: number);
	print(): number;
}

export type Class<Summer> = {
}

export class Main {
	protected constructor();
	static getSummer(): Class<Summer>;
	static cippa(x: number): {a: number};
}