// Generated by Haxe 4.0.5
(function ($hx_exports, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
class Summer {
	constructor(a,b) {
		this.a = a;
		this.b = b;
	}
	print() {
		return this.a + this.b;
	}
}
$hx_exports["Summer"] = Summer;
Summer.__name__ = true;
class Built {
	constructor() {
		this.h = 14;
		this.g = 6;
		this.f = 5;
		this.e = 2;
		this.d = 7;
		this._data = new tink_core_FutureTrigger();
		this._click = new tink_core_SignalTrigger();
		this.click = this._click;
		this.data = this._data;
		this.clickLeft = tink_core__$Signal_Signal_$Impl_$.filter(this.get_click(),function(e) {
			return e.x < 50.;
		});
		this.jsonData = this.get_data().map(function(b) {
			return b.toString();
		}).gather().map(JSON.parse).gather();
		this.a = Std.random(0);
		this.b = Std.random(0) + 1;
	}
	get_click() {
		return this.click;
	}
	get_data() {
		return this.data;
	}
	get_clickLeft() {
		return this.clickLeft;
	}
	get_jsonData() {
		return this.jsonData;
	}
	get_b() {
		return this.b;
	}
	get_c() {
		return 2;
	}
	get_d() {
		return 3;
	}
	get_e() {
		return 2 * this.e;
	}
	get_f() {
		return this.f;
	}
	set_f(param) {
		this.f = param;
		return param;
	}
	get_g() {
		return this.g;
	}
	set_g(param) {
		this.g = param << 1;
		return param;
	}
	get_h() {
		return this.h >>> 1;
	}
	set_h(param) {
		this.h = param << 1;
		return param;
	}
	get_i() {
		return this.get_h() + 1;
	}
	set_i(param) {
		this.set_h(param - 1);
		return param;
	}
	get_j() {
		return this.get_d() * 3;
	}
	get_k() {
		return this.get_d() * 4;
	}
	get_l() {
		return this.get_d() * 5;
	}
	static get_foo() {
		return Math.random();
	}
}
$hx_exports["Built"] = Built;
Built.__name__ = true;
class Counter {
	constructor(cb) {
		this.x = 0;
		this.timer = new haxe_Timer(1000);
		var _gthis = this;
		this.timer.run = function() {
			cb(_gthis.x++);
			return;
		};
	}
}
$hx_exports["Counter"] = Counter;
Counter.__name__ = true;
class Counter2 {
	constructor() {
		this.x = 0;
		this.trigger = new tink_core_SignalTrigger();
		this.signal = this.trigger;
		this.timer = new haxe_Timer(1000);
		var _gthis = this;
		this.timer.run = function() {
			_gthis.trigger.handlers.invoke(_gthis.x++);
			return;
		};
	}
}
$hx_exports["Counter2"] = Counter2;
Counter2.__name__ = true;
class Proxy {
	constructor() {
	}
	get_name() {
		var f = function(resolve,reject) {
			haxe_Log.trace({ field : "name"},{ fileName : "src/Main.hx", lineNumber : 100, className : "Proxy", methodName : "get_name"});
			resolve("name");
			return;
		};
		var this1 = tink_core__$Future_Future_$Impl_$.async(function(cb) {
			f(function(v) {
				cb(tink_core_Outcome.Success(v));
			},function(e) {
				cb(tink_core_Outcome.Failure(e));
			});
		},false);
		return new Promise(function(resolve1,reject1) {
			this1.handle(function(o) {
				switch(o._hx_index) {
				case 0:
					resolve1(o.data);
					break;
				case 1:
					reject1(new tink_core__$Promise_TinkError(o.failure));
					break;
				}
			});
		});
	}
	set_name(param) {
		haxe_Log.trace("name",{ fileName : "src/Main.hx", lineNumber : 107, className : "Proxy", methodName : "set_name", customParams : [param]});
		return param;
	}
	get_surname() {
		var f = function(resolve,reject) {
			haxe_Log.trace({ field : "surname"},{ fileName : "src/Main.hx", lineNumber : 100, className : "Proxy", methodName : "get_surname"});
			resolve("surname");
			return;
		};
		var this1 = tink_core__$Future_Future_$Impl_$.async(function(cb) {
			f(function(v) {
				cb(tink_core_Outcome.Success(v));
			},function(e) {
				cb(tink_core_Outcome.Failure(e));
			});
		},false);
		return new Promise(function(resolve1,reject1) {
			this1.handle(function(o) {
				switch(o._hx_index) {
				case 0:
					resolve1(o.data);
					break;
				case 1:
					reject1(new tink_core__$Promise_TinkError(o.failure));
					break;
				}
			});
		});
	}
	set_surname(param) {
		haxe_Log.trace("surname",{ fileName : "src/Main.hx", lineNumber : 107, className : "Proxy", methodName : "set_surname", customParams : [param]});
		return param;
	}
}
$hx_exports["Proxy"] = Proxy;
Proxy.__name__ = true;
class Main {
	static getSummer() {
		return Summer;
	}
	static cippa(x) {
		return { a : x + 1};
	}
	static main() {
		haxe_Log.trace("Hello, world!",{ fileName : "src/Main.hx", lineNumber : 120, className : "Main", methodName : "main"});
	}
}
$hx_exports["Main"] = Main;
Main.__name__ = true;
Math.__name__ = true;
class Std {
	static string(s) {
		return js_Boot.__string_rec(s,"");
	}
	static random(x) {
		if(x <= 0) {
			return 0;
		} else {
			return Math.floor(Math.random() * x);
		}
	}
}
Std.__name__ = true;
var haxe_StackItem = $hxEnums["haxe.StackItem"] = { __ename__ : true, __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"]
	,CFunction: {_hx_index:0,__enum__:"haxe.StackItem",toString:$estr}
	,Module: ($_=function(m) { return {_hx_index:1,m:m,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["m"],$_)
	,FilePos: ($_=function(s,file,line,column) { return {_hx_index:2,s:s,file:file,line:line,column:column,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["s","file","line","column"],$_)
	,Method: ($_=function(classname,method) { return {_hx_index:3,classname:classname,method:method,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["classname","method"],$_)
	,LocalFunction: ($_=function(v) { return {_hx_index:4,v:v,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["v"],$_)
};
class haxe_Log {
	static formatOutput(v,infos) {
		var str = Std.string(v);
		if(infos == null) {
			return str;
		}
		var pstr = infos.fileName + ":" + infos.lineNumber;
		if(infos.customParams != null) {
			var _g = 0;
			var _g1 = infos.customParams;
			while(_g < _g1.length) str += ", " + Std.string(_g1[_g++]);
		}
		return pstr + ": " + str;
	}
	static trace(v,infos) {
		var str = haxe_Log.formatOutput(v,infos);
		if(typeof(console) != "undefined" && console.log != null) {
			console.log(str);
		}
	}
}
haxe_Log.__name__ = true;
class haxe_Timer {
	constructor(time_ms) {
		var me = this;
		this.id = setInterval(function() {
			me.run();
		},time_ms);
	}
	stop() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	run() {
	}
	static delay(f,time_ms) {
		var t = new haxe_Timer(time_ms);
		t.run = function() {
			t.stop();
			f();
		};
		return t;
	}
}
haxe_Timer.__name__ = true;
var haxe_ds_Option = $hxEnums["haxe.ds.Option"] = { __ename__ : true, __constructs__ : ["Some","None"]
	,Some: ($_=function(v) { return {_hx_index:0,v:v,__enum__:"haxe.ds.Option",toString:$estr}; },$_.__params__ = ["v"],$_)
	,None: {_hx_index:1,__enum__:"haxe.ds.Option",toString:$estr}
};
class haxe_io_Bytes {
	constructor(data) {
		this.length = data.byteLength;
		this.b = new Uint8Array(data);
		this.b.bufferValue = data;
		data.hxBytes = this;
		data.bytes = this.b;
	}
	getString(pos,len,encoding) {
		if(pos < 0 || len < 0 || pos + len > this.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		if(encoding == null) {
			encoding = haxe_io_Encoding.UTF8;
		}
		var s = "";
		var b = this.b;
		var i = pos;
		var max = pos + len;
		switch(encoding._hx_index) {
		case 0:
			while(i < max) {
				var c = b[i++];
				if(c < 128) {
					if(c == 0) {
						break;
					}
					s += String.fromCodePoint(c);
				} else if(c < 224) {
					var code = (c & 63) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code);
				} else if(c < 240) {
					var code1 = (c & 31) << 12 | (b[i++] & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code1);
				} else {
					var u = (c & 15) << 18 | (b[i++] & 127) << 12 | (b[i++] & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(u);
				}
			}
			break;
		case 1:
			while(i < max) {
				var c1 = b[i++] | b[i++] << 8;
				s += String.fromCodePoint(c1);
			}
			break;
		}
		return s;
	}
	toString() {
		return this.getString(0,this.length);
	}
}
haxe_io_Bytes.__name__ = true;
var haxe_io_Encoding = $hxEnums["haxe.io.Encoding"] = { __ename__ : true, __constructs__ : ["UTF8","RawNative"]
	,UTF8: {_hx_index:0,__enum__:"haxe.io.Encoding",toString:$estr}
	,RawNative: {_hx_index:1,__enum__:"haxe.io.Encoding",toString:$estr}
};
var haxe_io_Error = $hxEnums["haxe.io.Error"] = { __ename__ : true, __constructs__ : ["Blocked","Overflow","OutsideBounds","Custom"]
	,Blocked: {_hx_index:0,__enum__:"haxe.io.Error",toString:$estr}
	,Overflow: {_hx_index:1,__enum__:"haxe.io.Error",toString:$estr}
	,OutsideBounds: {_hx_index:2,__enum__:"haxe.io.Error",toString:$estr}
	,Custom: ($_=function(e) { return {_hx_index:3,e:e,__enum__:"haxe.io.Error",toString:$estr}; },$_.__params__ = ["e"],$_)
};
class js__$Boot_HaxeError extends Error {
	constructor(val) {
		super();
		this.val = val;
		if(Error.captureStackTrace) {
			Error.captureStackTrace(this,js__$Boot_HaxeError);
		}
	}
}
js__$Boot_HaxeError.__name__ = true;
class js_Boot {
	static __string_rec(o,s) {
		if(o == null) {
			return "null";
		}
		if(s.length >= 5) {
			return "<...>";
		}
		var t = typeof(o);
		if(t == "function" && (o.__name__ || o.__ename__)) {
			t = "object";
		}
		switch(t) {
		case "function":
			return "<function>";
		case "object":
			if(o.__enum__) {
				var e = $hxEnums[o.__enum__];
				var n = e.__constructs__[o._hx_index];
				var con = e[n];
				if(con.__params__) {
					s = s + "\t";
					return n + "(" + ((function($this) {
						var $r;
						var _g = [];
						{
							var _g1 = 0;
							var _g2 = con.__params__;
							while(true) {
								if(!(_g1 < _g2.length)) {
									break;
								}
								var p = _g2[_g1];
								_g1 = _g1 + 1;
								_g.push(js_Boot.__string_rec(o[p],s));
							}
						}
						$r = _g;
						return $r;
					}(this))).join(",") + ")";
				} else {
					return n;
				}
			}
			if(((o) instanceof Array)) {
				var str = "[";
				s += "\t";
				var _g3 = 0;
				var _g11 = o.length;
				while(_g3 < _g11) {
					var i = _g3++;
					str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
				}
				str += "]";
				return str;
			}
			var tostr;
			try {
				tostr = o.toString;
			} catch( e1 ) {
				var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
				return "???";
			}
			if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
				var s2 = o.toString();
				if(s2 != "[object Object]") {
					return s2;
				}
			}
			var str1 = "{\n";
			s += "\t";
			var hasp = o.hasOwnProperty != null;
			var k = null;
			for( k in o ) {
			if(hasp && !o.hasOwnProperty(k)) {
				continue;
			}
			if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
				continue;
			}
			if(str1.length != 2) {
				str1 += ", \n";
			}
			str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
			}
			s = s.substring(1);
			str1 += "\n" + s + "}";
			return str1;
		case "string":
			return o;
		default:
			return String(o);
		}
	}
}
js_Boot.__name__ = true;
class tink_core__$Callback_Callback_$Impl_$ {
	static invoke(this1,data) {
		if(tink_core__$Callback_Callback_$Impl_$.depth < 500) {
			tink_core__$Callback_Callback_$Impl_$.depth++;
			this1(data);
			tink_core__$Callback_Callback_$Impl_$.depth--;
		} else {
			var _e = this1;
			var f = function(data1) {
				tink_core__$Callback_Callback_$Impl_$.invoke(_e,data1);
			};
			var data2 = data;
			tink_core__$Callback_Callback_$Impl_$.defer(function() {
				f(data2);
			});
		}
	}
	static defer(f) {
		haxe_Timer.delay(f,0);
	}
}
tink_core__$Callback_Callback_$Impl_$.__name__ = true;
class tink_core__$Callback_ListCell {
	constructor(cb,list) {
		if(cb == null) {
			throw new js__$Boot_HaxeError("callback expected but null received");
		}
		this.cb = cb;
		this.list = list;
	}
	cancel() {
		if(this.list != null) {
			var list = this.list;
			this.cb = null;
			this.list = null;
			if(--list.used < list.used >> 1) {
				list.compact();
			}
		}
	}
}
tink_core__$Callback_ListCell.__name__ = true;
class tink_core_CallbackList {
	constructor() {
		this.busy = false;
		this.queue = [];
		this.used = 0;
		this.cells = [];
	}
	ondrain() {
	}
	invoke(data,destructive) {
		if(this.busy) {
			var f = $bind(this,this.invoke);
			var data1 = data;
			var destructive1 = destructive;
			var tmp = function() {
				f(data1,destructive1);
				return;
			};
			this.queue.push(tmp);
		} else {
			this.busy = true;
			var length = this.cells.length;
			var _g = 0;
			while(_g < length) {
				var _this = this.cells[_g++];
				if(_this.list != null) {
					tink_core__$Callback_Callback_$Impl_$.invoke(_this.cb,data);
				}
			}
			this.busy = false;
			if(destructive) {
				var added = this.cells.length - length;
				var _g2 = 0;
				while(_g2 < length) {
					var _this1 = this.cells[_g2++];
					_this1.cb = null;
					_this1.list = null;
				}
				var _g4 = 0;
				while(_g4 < added) {
					var i = _g4++;
					this.cells[i] = this.cells[length + i];
				}
				this.resize(added);
			} else if(this.used < this.cells.length) {
				this.compact();
			}
			if(this.queue.length > 0) {
				(this.queue.shift())();
			}
		}
	}
	compact() {
		if(this.busy) {
			return;
		} else if(this.used == 0) {
			this.resize(0);
			this.ondrain();
		} else {
			var compacted = 0;
			var _g = 0;
			var _g1 = this.cells.length;
			while(_g < _g1) {
				var i = _g++;
				var _g2 = this.cells[i];
				if(_g2.cb != null) {
					if(compacted != i) {
						this.cells[compacted] = _g2;
					}
					if(++compacted == this.used) {
						break;
					}
				}
			}
			this.resize(this.used);
		}
	}
	resize(length) {
		this.cells.length = length;
	}
}
tink_core_CallbackList.__name__ = true;
class tink_core_TypedError {
	constructor(code,message,pos) {
		if(code == null) {
			code = 500;
		}
		this.code = code;
		this.message = message;
		this.pos = pos;
		this.exceptionStack = [];
		this.callStack = [];
	}
}
tink_core_TypedError.__name__ = true;
class tink_core__$Lazy_LazyConst {
	constructor(value) {
		this.value = value;
	}
	get() {
		return this.value;
	}
	map(f) {
		var _gthis = this;
		return new tink_core__$Lazy_LazyFunc(function() {
			return f(_gthis.value);
		});
	}
}
tink_core__$Lazy_LazyConst.__name__ = true;
class tink_core__$Future_SyncFuture {
	constructor(value) {
		this.value = value;
	}
	map(f) {
		return new tink_core__$Future_SyncFuture(this.value.map(f));
	}
	handle(cb) {
		tink_core__$Callback_Callback_$Impl_$.invoke(cb,this.value.get());
		return null;
	}
	gather() {
		return this;
	}
}
tink_core__$Future_SyncFuture.__name__ = true;
class tink_core__$Future_Future_$Impl_$ {
	static async(f,lazy) {
		if(lazy == null) {
			lazy = false;
		}
		if(lazy) {
			return new tink_core__$Future_SuspendableFuture(function($yield) {
				f($yield);
				return null;
			});
		} else {
			var op = new tink_core_FutureTrigger();
			tink_core__$Callback_Callback_$Impl_$.invoke(f,$bind(op,op.trigger));
			return op;
		}
	}
}
tink_core__$Future_Future_$Impl_$.__name__ = true;
class tink_core_FutureTrigger {
	constructor() {
		this.list = new tink_core_CallbackList();
	}
	handle(callback) {
		var _g = this.list;
		if(_g == null) {
			tink_core__$Callback_Callback_$Impl_$.invoke(callback,this.result);
			return null;
		} else {
			var node = new tink_core__$Callback_ListCell(callback,_g);
			_g.cells.push(node);
			_g.used++;
			return node;
		}
	}
	map(f) {
		if(this.list == null) {
			return new tink_core__$Future_SyncFuture(new tink_core__$Lazy_LazyConst(f(this.result)));
		} else {
			var ret = new tink_core_FutureTrigger();
			var _this = this.list;
			var node = new tink_core__$Callback_ListCell(function(v) {
				var node1 = f(v);
				ret.trigger(node1);
			},_this);
			_this.cells.push(node);
			_this.used++;
			return ret;
		}
	}
	gather() {
		return this;
	}
	trigger(result) {
		if(this.list == null) {
			return false;
		} else {
			var list = this.list;
			this.list = null;
			this.result = result;
			list.invoke(result,true);
			return true;
		}
	}
}
tink_core_FutureTrigger.__name__ = true;
class tink_core__$Future_SuspendableFuture {
	constructor(wakeup) {
		this.suspended = true;
		var _gthis = this;
		this.wakeup = wakeup;
		this.callbacks = new tink_core_CallbackList();
		this.callbacks.ondrain = function() {
			if(_gthis.callbacks != null) {
				_gthis.suspended = true;
				var this1 = _gthis.link;
				if(this1 != null) {
					this1.cancel();
				}
				_gthis.link = null;
			}
		};
	}
	trigger(value) {
		var _g = this.callbacks;
		if(_g != null) {
			this.callbacks = null;
			this.suspended = false;
			this.result = value;
			this.link = null;
			this.wakeup = null;
			_g.invoke(value,true);
		}
	}
	handle(callback) {
		if(this.callbacks == null) {
			tink_core__$Callback_Callback_$Impl_$.invoke(callback,this.result);
			return null;
		} else {
			var _this = this.callbacks;
			var node = new tink_core__$Callback_ListCell(callback,_this);
			_this.cells.push(node);
			_this.used++;
			if(this.suspended) {
				this.suspended = false;
				this.link = this.wakeup($bind(this,this.trigger));
			}
			return node;
		}
	}
	map(f) {
		var _gthis = this;
		return new tink_core__$Future_SuspendableFuture(function($yield) {
			return _gthis.handle(function(res) {
				var tmp = f(res);
				$yield(tmp);
			});
		});
	}
	gather() {
		return this;
	}
}
tink_core__$Future_SuspendableFuture.__name__ = true;
class tink_core__$Lazy_LazyFunc {
	constructor(f) {
		this.f = f;
	}
	get() {
		if(this.f != null) {
			this.result = this.f();
			this.f = null;
		}
		return this.result;
	}
	map(f) {
		var _gthis = this;
		return new tink_core__$Lazy_LazyFunc(function() {
			var tmp = _gthis.get();
			return f(tmp);
		});
	}
}
tink_core__$Lazy_LazyFunc.__name__ = true;
var tink_core_Outcome = $hxEnums["tink.core.Outcome"] = { __ename__ : true, __constructs__ : ["Success","Failure"]
	,Success: ($_=function(data) { return {_hx_index:0,data:data,__enum__:"tink.core.Outcome",toString:$estr}; },$_.__params__ = ["data"],$_)
	,Failure: ($_=function(failure) { return {_hx_index:1,failure:failure,__enum__:"tink.core.Outcome",toString:$estr}; },$_.__params__ = ["failure"],$_)
};
class tink_core__$Promise_TinkError extends Error {
	constructor(e) {
		super(e.message);
		this.data = e;
	}
}
tink_core__$Promise_TinkError.__name__ = true;
class tink_core__$Signal_Signal_$Impl_$ {
	static filter(this1,f,gather) {
		if(gather == null) {
			gather = true;
		}
		var ret = new tink_core__$Signal_SimpleSignal(function(cb) {
			return this1.listen(function(result) {
				if(f(result)) {
					tink_core__$Callback_Callback_$Impl_$.invoke(cb,result);
				}
			});
		});
		if(gather) {
			return tink_core__$Signal_Signal_$Impl_$.gather(ret);
		} else {
			return ret;
		}
	}
	static gather(this1) {
		var ret = tink_core__$Signal_Signal_$Impl_$.trigger();
		this1.listen(function(x) {
			ret.handlers.invoke(x);
		});
		return ret;
	}
	static trigger() {
		return new tink_core_SignalTrigger();
	}
}
tink_core__$Signal_Signal_$Impl_$.__name__ = true;
class tink_core__$Signal_SimpleSignal {
	constructor(f) {
		this.f = f;
	}
	listen(cb) {
		return this.f(cb);
	}
}
tink_core__$Signal_SimpleSignal.__name__ = true;
class tink_core_SignalTrigger {
	constructor() {
		this.handlers = new tink_core_CallbackList();
	}
	listen(cb) {
		var _this = this.handlers;
		var node = new tink_core__$Callback_ListCell(cb,_this);
		_this.cells.push(node);
		_this.used++;
		return node;
	}
}
tink_core_SignalTrigger.__name__ = true;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
tink_core__$Callback_Callback_$Impl_$.depth = 0;
Main.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
